GET https://localhost:5009/users/all HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjI0MUVBRDgwNTkxREIyQzAxMjE3RjU5NEExQUQxQzgyIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NzI0NjgxNzEsImV4cCI6MTY3MjQ3MTc3MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEvcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoiZXh0ZXJuYWwiLCJzdWIiOiI0YzgwMjRiMy1kN2UwLTQzMTUtYjJlYi02NmRmY2I4MjU5MTMiLCJhdXRoX3RpbWUiOjE2NzI0NjgxNzEsImlkcCI6ImxvY2FsIiwianRpIjoiMTJCNjkzQjAxNzcxMTdGNEM4Q0RDQTA0N0JGODE2QzkiLCJpYXQiOjE2NzI0NjgxNzEsInNjb3BlIjpbIk9ubGluZVNob3AuV2ViIl0sImFtciI6WyJwd2QiXX0.HTQzjGoJ2sTmR4JIZZBBS3H34FjqCQ27VrPP-IcpujotlU3YEsxnpgzC3m849G0pkFtEBocwZgv6EGh97vXxyBfEXdkZvX89CWZmkOiPBzSNx-FzNW8vHJkjw7-ErsnynZbsnoTCCkpF08nwz_HCcfYEsJl8S2IzXRO5BStSr5ijRx1l6QsQFiJ-CKGgs12UWK3NJUIs4vpkpek8VIPdz399-pJKyVv9p93avHjedtYGGPnscwysf1qG_hVGiQUM7qDvItrPunGb29IIKoVtbVMUZGW7PxTtaklgSX7Wht-Dx2T3vBqck-7PwnfBTroxq8IeNZQXesVW0QdUNUOA7Q

